### ISSUE TITLE
Небольшая опечатка - "на локальную компьютер"

### ISSUE THREAD

**Issue by ArtKaretnikov** [githubjeka/yii2-tutorial#11]
Доброго. 

Прямо на первой странице руководства, где "настройка Git"
"git clone клонирует удалённый репозиторий на локальную компьютер"

Коллега, я не уверен, что такие вещи надо править, некоторые обижаются на опечатки, но если надо - я вам еще напишу.

**Comment by githubjeka** [comment]
Спасибо, я не обижаюсь. Присылайте.
