### ISSUE TITLE
Ошибка в занятии "Сохранение реляционных данных"

### ISSUE THREAD

**Issue by verget** [githubjeka/yii2-tutorial#14]
Момент с подстановкой списка звёзд на странице создания новой планеты, строка
"echo $form->field($model, 'planet')->dropDownList($stars, ['prompt' => 'Выберите звезду']);"
вместо свойства 'planet' должно быть "star_id", аналогично в примере выше (без ArrayHelper)

**Comment by verget** [comment]
В тексте урока ".. Теперь к тесту добавим команду на открытие страницы с формой. ля этого нужно создать объект этой страницы." Опечатка, пропущено "д"

**Comment by githubjeka** [comment]
@verget Спасибо.
