### ISSUE TITLE
Знакомство с тестированием ссылка на  cmder

### ISSUE THREAD

**Issue by des1roer** [githubjeka/yii2-tutorial#5]
имеет смысл сообщить о http://open-server.ru/ и его консоли "дополнительно"->"консоль"

**Comment by githubjeka** [comment]
Я им не пользуюсь, что там?

**Comment by des1roer** [comment]
удобная консоль. локальный сервер и консоль что-то вроде http://4.bp.blogspot.com/-UjONhFaCI1Y/VYOwLA7iq2I/AAAAAAAAAeI/-cBLmi4JCps/s1600/Screenshot_2.png

**Comment by des1roer** [comment]
или так 
![img 5](https://cloud.githubusercontent.com/assets/10970793/8267354/10f0377a-1777-11e5-9d46-0d5409e6a657.png)
