### ISSUE TITLE
Работа с реляционными данными по поводу названия таблиц

### ISSUE THREAD

**Issue by des1roer** [githubjeka/yii2-tutorial#6]
хорошим тоном считается называть сущность в lowercase или under_score, т.к. например при работе с Postgres UpperCase таблицы и поля нужно обрамлять двойными кавычками

**Comment by des1roer** [comment]
в строке 
Приведём код миграции к следующему виду:
можно дать путь до миграции 

```
     \yii2-tutorial\yii2-app-advanced\console\migrations\m150620_054003_create_asto_tables.php
```

**Comment by des1roer** [comment]
в строке 

Обратите внимание, что имена таблиц имеют вид "{{%name}}". Это необходимо, если вы захотите использовать префикс в именах таблиц, который можно установить через конфигурацию компонента db:

уместно указать путь

```
     \yii2-tutorial\yii2-app-advanced\common\config\main-local.php
```

а то с 3мя местами под конфиги запутаться можно

**Comment by githubjeka** [comment]
Спасибо.
